# Generated by Django 5.1.6 on 2025-02-25 04:48

import app1.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KYCStatus',
            fields=[
                ('kyc_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(max_length=255, null=True)),
                ('asset_code', models.CharField(max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('vendor_supplier', models.CharField(max_length=255, null=True)),
                ('invoice_number', models.CharField(max_length=100, null=True, unique=True)),
                ('depreciation_method', models.CharField(max_length=100, null=True)),
                ('depreciation_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('useful_life_years', models.IntegerField(null=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to=app1.models.asset_image_upload_path)),
                ('documents', models.FileField(blank=True, null=True, upload_to=app1.models.asset_document_upload_path)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_due', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_method', models.CharField(blank=True, max_length=255, null=True)),
                ('disposal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.assettype')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer_id', models.IntegerField()),
                ('buyer_type', models.CharField(max_length=20)),
                ('seller_id', models.IntegerField()),
                ('seller_type', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('rent', 'Rent'), ('lease', 'Lease')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.asset')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to=app1.models.user_image_upload_path)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_users', to='app1.user')),
                ('kyc_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.kycstatus')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.status')),
                ('user_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('kyc_id', models.AutoField(primary_key=True, serialize=False)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('pan_pdf', models.FileField(blank=True, null=True, upload_to=app1.models.user_kyc_upload_path)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('aadhaar_pdf', models.FileField(blank=True, null=True, upload_to=app1.models.user_kyc_upload_path)),
                ('kyc_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.kycstatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_details', to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=255)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='app1.user')),
            ],
        ),
    ]
